Improve CI
renuo/redmine_tracky pull request #124
Opened 2024-01-26 09:19 UTC by hunchr

TICKET-21286

- Add caching
- Reduce time from **~2m 15s** to **~1m 25s**
- Use `redmine/5.1-stable` instead of `redmine/master` branch

2024-01-26 11:14 UTC, schmijos requested changes

2024-01-30 06:57 UTC, hunchr commented on bin/setup
> +bundle exec rake db:drop db:create db:migrate db:seed redmine:sample_data:seed
Oh right, this is really dangerous for prod

2024-02-08 11:28 UTC, schmijos commented on bin/setup
> +db=config/database.yml.example
I'd generally like to support SQLite, Postgres and MySQL.

2024-02-08 11:29 UTC, schmijos approved these changes

2024-02-08 11:32 UTC, merged

2024-02-08 12:53 UTC, hunchr commented on bin/setup
> +db=config/database.yml.example
> by default we don't want redmine_tracky/.github/database.yml?

this is only used if the env variable $GITHUB_ACTIONS is set