Tracky Refactoring
renuo/redmine_tracky pull request #142
Opened 2024-05-24 06:51 UTC by CuddlyBunion341

2024-05-31 11:51 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +  def upsert
```suggestion
  def create_or_update
```

2024-05-31 11:54 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    return cancel_timer if params[:cancel]
```suggestion
    return cancel_timer if params[:cancel].present?
```

2024-05-31 11:56 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    return cancel_timer if params[:cancel]
Keep cancel as separate endpoint? Look into TimerSession attributes for cancelling.

Follow Rails conventions for params.

2024-05-31 12:01 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    @current_timer_session = SessionCreator.new(User.current, timer_params, params[:commit]).create
Refactor params[:commit]??

2024-05-31 12:02 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    @current_timer_session = SessionCreator.new(User.current, timer_params, params[:commit]).create
Command params hash

2024-05-31 12:03 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    @current_timer_session = SessionCreator.new(User.current, timer_params, params[:commit]).create
Investigate ActiveModel::Attributes

2024-05-31 12:10 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +      stop_timer
Idea: All render calls happen inside action?

2024-05-31 12:11 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    @current_timer_session.destroy
Missing errorhandling

2024-05-31 12:11 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    render :cancel, layout: false and return
```suggestion
    render :cancel, layout: false
```

2024-05-31 12:12 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    render :cancel, layout: false and return
Add respond to blocks.

2024-05-31 12:18 UTC, CuddlyBunion341 commented on app/models/timer_session.rb
> +  def validate_enough_time
```suggestion
  def validate_minimal_duration
```

2024-05-31 12:18 UTC, CuddlyBunion341 commented on app/views/shared/_js_variables.html.erb
> +  RedmineTracky.trackerUpdatePath = "<%= j(time_tracker_upsert_url) %>";
Update path name

2024-05-31 12:21 UTC, CuddlyBunion341 commented on assets.src/src/redmine-tracky/controllers/timer-controller.ts
> +    const formattedDuration = duration.toFormat('hh:mm:ss').replaceAll('-', '')
Verify ISO standard for negative timestamp

2024-05-31 12:24 UTC, CuddlyBunion341 commented on assets/javascripts/redmine-tracky.js
Idea: Reduce JS

2024-05-31 12:24 UTC, CuddlyBunion341 commented on config/routes.rb
> +post 'time_tracker/upsert', to: 'time_tracker#upsert', as: :time_tracker_upsert
Update route

2024-05-31 12:27 UTC, CuddlyBunion341 commented on app/views/timer_sessions/_timer_container.html.erb
> +            placeholder: t('timer_sessions.messaging.comments_placeholder'), class: 'w-100',
Maybe hide date at input field

2024-06-05 06:04 UTC, CuddlyBunion341 commented on assets.src/src/redmine-tracky/controllers/timer-controller.ts
> +    const formattedDuration = duration.toFormat('hh:mm:ss').replaceAll('-', '')
According to the ISO_8601 standard, there seems to be a notation, where the offset is perfixed with a 'minus' sign to imply negative time:
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

2024-06-07 11:54 UTC, CuddlyBunion341 commented on app/components/timer_session_entry_component.rb
> +    User.current.allowed_to_globally?(action: :destroy, controller: 'timer_sessions')
Maybe in another PR...

2024-06-10 14:13 UTC, schmijos requested changes
Please extract the input form re-arrangements to a new PR. I'd like to be able to roll-back the condensed form view if user feedback is bad.

2024-06-11 06:48 UTC, CuddlyBunion341 commented
Thanks for the review @schmijos! I should have updated the Pull Request description explaining that the changes to the tracky layout have been reverted. You should also be able to see only the paths changed in the views and nothing else. I will open another PR with the requested changes.

2024-06-12 11:42 UTC, CuddlyBunion341 commented on app/controllers/time_tracker_controller.rb
> +    cancel_timer if params[:cancel].present?
```suggestion
```

2024-06-26 08:06 UTC, schmijos approved these changes
Looks good! Let's make sure we test this properly on develop.

2024-06-26 12:11 UTC, CuddlyBunion341 commented on app/models/unfinished_timer_session_validator.rb
> +    return if @record.timer_start.blank? || @record.timer_end.blank?
True, thanks for pointing it out

2024-06-26 12:11 UTC, CuddlyBunion341 commented on app/models/finished_timer_session_validator.rb
> +      ) > SettingsManager.max_hours_recorded_per_day.to_f
More readable for sure.

2024-06-26 12:19 UTC, merged

2024-06-26 12:58 UTC, schmijos commented on app/models/unfinished_timer_session_validator.rb
> +    return if @record.timer_start.blank? || @record.timer_end.blank?
Why wasn't this catched by a test?

2024-06-26 13:18 UTC, CuddlyBunion341 commented on app/models/unfinished_timer_session_validator.rb
> +    return if @record.timer_start.blank? || @record.timer_end.blank?
The validations have been tested indirectly by the request tests. The timer_start should be set in all scenarios.